### ISSUE TITLE
Tokens to be considered for Auro inputoptions WC

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/AuroDesignTokens#27]
## Reference 

https://github.com/AlaskaAirlines/ods-inputoptions/issues/10

## Issue

@blackfalcon @tsalright Here is the list of tokens I derived from @vidalmenAS's mocks. 
To match some of these mocks, the border color had to be pulled from the text block. Will we need new tokens in the right category for these?

```
Checkbox:

    Normal:

        Text: 
            font-color: --auro-color-text-primary-on-light
        Unselected
            background: --auro-color-background-lightest
            border-radius: 6px
            border: 1px solid --auro-color-text-primary-on-light
            height: --auro-lg
        Checked
            background: --auro-color-ui-default-on-light
            border-radius: 6px
            border: 1px solid --auro-color-border-active-on-light
            height: --auro-lg
        Focus-Visible:
            border-radius: --auro-xxxs
            border: 2px solid --auro-color-ui-default-on-light
            height: 28px;
        Barred
            background: --auro-color-background-lightest
            border-radius: 6px
            border: 1px solid --auro-color-text-primary-on-light
            height: --auro-lg
    OnDark:
        Text: 
            font-color: --auro-color-text-primary-on-dark
        Unselected
            background: --auro-color-base-black-opacity-15
            border-radius: 6px
            border: 1px solid --auro-color-border-divider-on-dark
            height: --auro-lg
        Checked
            background: --auro-color-ui-default-on-dark
            border-radius: 6px
            border: 1px solid --auro-color-border-active-on-dark
            height: --auro-lg
        Focus-Visible:
            border-radius: --auro-xxxs
            border: 2px solid --auro-color-ui-default-on-dark
            height: 28px;
        Barred
            background: --auro-color-base-black-opacity-15
            border-radius: 6px
            border: 1px solid --auro-color-border-divider-on-dark
            height: --auro-lg

Spacing between Checkbox and Label: --auro-xs
```
